# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
HUGGING_FACE_API_KEY = "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"



[server]
enableStaticServing = true



[theme]
base="light"
textColor="#717cbb"
